# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecruitSuite' do
  pod 'AppCenter/Crashes', '~> 1.13.0'
  pod 'AppCenter/Analytics', '~> 1.13.0'
  pod 'AppCenterReactNativeShared', '~> 1.12.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RecruitSuite



  platform :ios, '9.0'
  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNDefaultPreference', :path => '../node_modules/react-native-default-preference'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-sms', :path => '../node_modules/react-native-sms'

  target 'RecruitSuiteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
